# Generated by Django 4.1.7 on 2023-03-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_quantity_product_count_remove_owner_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='product',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='time',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='label',
        ),
        migrations.AddField(
            model_name='product',
            name='value',
            field=models.CharField(default=1, max_length=210),
            preserve_default=False,
        ),
    ]
