# Generated by Django 4.1.7 on 2023-03-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_product_owner_category_rename_time_owner_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='date',
            field=models.IntegerField(),
        ),
    ]
