# Generated by Django 4.1.7 on 2023-03-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_owner_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='date',
            field=models.CharField(max_length=210),
        ),
    ]
