# Generated by Django 4.1.7 on 2023-03-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_owner_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
